# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

import bisect
import os
import pickle

import torch
import torch.nn.functional as F
import torch.utils.data
import zarr


PROSTATE_COHORTS = ("UPenn_OTLS5", "UPenn_OTLS4", "DoD", "Oxford")
PROSTATE_CACHE_SUFFIXES = ("p128_s0", "p256_s0", "p256_s128")


def resolve_loco_cohorts(cohorts, leave_one_cohort):
    cohorts = list(cohorts)
    if leave_one_cohort:
        if leave_one_cohort not in cohorts:
            raise ValueError(
                "leave_one_cohort must be one of {}. Got {}".format(
                    cohorts, leave_one_cohort
                )
            )
        cohorts = [cohort for cohort in cohorts if cohort != leave_one_cohort]
    if not cohorts:
        raise ValueError("No training cohorts remain after leave-one-cohort-out split")
    return cohorts


def infer_chunk_size(cache_suffix):
    if cache_suffix.startswith("p128"):
        return 128
    if cache_suffix.startswith("p256"):
        return 256
    raise ValueError("Cannot infer chunk size from cache suffix: {}".format(cache_suffix))


class ProstatePatchDataset(torch.utils.data.Dataset):
    """Dataset for 3D RGB prostate zarr patches generated by create_metadata.py."""

    def __init__(
        self,
        metadata_cache_dir,
        cohorts,
        cache_suffix,
        input_size,
        num_frames,
        mean=(0.45, 0.45, 0.45),
        std=(0.225, 0.225, 0.225),
        normalize=True,
    ):
        if cache_suffix not in PROSTATE_CACHE_SUFFIXES:
            raise ValueError(
                "cache_suffix must be one of {}. Got {}".format(
                    PROSTATE_CACHE_SUFFIXES, cache_suffix
                )
            )

        self.metadata_cache_dir = metadata_cache_dir
        self.cohorts = list(cohorts)
        self.cache_suffix = cache_suffix
        self.input_size = int(input_size)
        self.num_frames = int(num_frames)
        self.normalize = normalize
        self.mean = torch.tensor(mean, dtype=torch.float32).view(3, 1, 1, 1)
        self.std = torch.tensor(std, dtype=torch.float32).view(3, 1, 1, 1)

        self._slides = []
        self._cumulative_sizes = []
        total = 0

        for cohort in self.cohorts:
            cache_path = os.path.join(
                metadata_cache_dir, "cache_{}_{}.pkl".format(cohort, cache_suffix)
            )
            if not os.path.exists(cache_path):
                raise FileNotFoundError("Metadata cache not found: {}".format(cache_path))

            with open(cache_path, "rb") as f:
                cache = pickle.load(f)

            paths = cache["paths"]
            num_patches = cache["num_patches"]
            slide_ids = cache.get("slide_ids", [None] * len(paths))
            valid_indices = cache.get("valid_indices")

            for i, path in enumerate(paths):
                n_patches = int(num_patches[i])
                if n_patches <= 0:
                    continue

                indices = None
                if valid_indices is not None:
                    indices = valid_indices[i]
                    if len(indices) != n_patches:
                        raise ValueError(
                            "Cache {} has inconsistent valid_indices for slide {}".format(
                                cache_path, slide_ids[i]
                            )
                        )

                self._slides.append(
                    {
                        "cohort": cohort,
                        "slide_id": slide_ids[i],
                        "path": path,
                        "num_patches": n_patches,
                        "valid_indices": indices,
                    }
                )
                total += n_patches
                self._cumulative_sizes.append(total)

        if total == 0:
            raise RuntimeError(
                "No patches found for cohorts {} with cache suffix {}".format(
                    self.cohorts, cache_suffix
                )
            )

        self._zarr_cache = {}

    def __len__(self):
        return self._cumulative_sizes[-1]

    @property
    def num_slides(self):
        return len(self._slides)

    def _get_slide_and_patch_index(self, index):
        if index < 0:
            index += len(self)
        if index < 0 or index >= len(self):
            raise IndexError(index)

        slide_idx = bisect.bisect_right(self._cumulative_sizes, index)
        prev = 0 if slide_idx == 0 else self._cumulative_sizes[slide_idx - 1]
        local_idx = index - prev
        slide = self._slides[slide_idx]

        valid_indices = slide["valid_indices"]
        if valid_indices is not None:
            local_idx = valid_indices[local_idx]
        return slide, local_idx

    def _open_zarr(self, path):
        group = self._zarr_cache.get(path)
        if group is None:
            group = zarr.open_group(path, mode="r")
            self._zarr_cache[path] = group
        return group

    def __getitem__(self, index):
        slide, patch_idx = self._get_slide_and_patch_index(index)
        group = self._open_zarr(slide["path"])
        patch = group["patches"][patch_idx]

        patch = torch.as_tensor(patch, dtype=torch.float32).div_(255.0)
        if patch.ndim != 4 or patch.shape[0] != 3:
            raise RuntimeError(
                "Expected patch shape [3, T, H, W], got {} from {}".format(
                    tuple(patch.shape), slide["path"]
                )
            )

        target_shape = (self.num_frames, self.input_size, self.input_size)
        if tuple(patch.shape[1:]) != target_shape:
            patch = F.interpolate(
                patch.unsqueeze(0),
                size=target_shape,
                mode="trilinear",
                align_corners=False,
            ).squeeze(0)

        if self.normalize:
            patch = (patch - self.mean) / self.std

        return patch, torch.tensor(0, dtype=torch.long)
